import Head from 'next/head';
// import Image from 'next/image';
import styles from '../styles/Home.module.css';
//importation de fausse donnée
import Button from '../public/components/Button';
import Card from '../public/components/Card';
import { useState } from 'react';
import React from 'react';

export default function Home({ initialPokemon }) {
  const [pokemon, setPokemon] = useState(initialPokemon);

  const toggleNav = () => {
    setToggleMenu(!toggleMenu);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>T&C</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}

      <header className="header">
        <h2 className="title-header">Tendance & Classe</h2>

        

        <nav className="nav-header">
          <ul>
            <Button
              label="inscription "
              onClick={toggleNav}
              classList="btn-nav"
            />
            <Button
              label="connexion "
              onClick={toggleNav}
              classList="btn-nav"
            />
            <Button label="admin " onClick={toggleNav} classList="btn-nav" />
          </ul>
        </nav>
      </header>

      {/* content    */}

      <main>

      <div>
          {pokemon.results.map((monster, index) => (
            <Card 
            title="bulbizare" 
            
            
            price="12"
            description="le miroir de la chambre casser"
            key={index} pokemon={monster} index={index} />
          ))}
          
        </div>
        
        
          
      </main>
    </div>
  );
}

export async function getStaticProps(context) {
  const response = await fetch('https://pokeapi.co/api/v2/pokemon');

  const initialPokemon = await response.json();

  return {
    props: {
      initialPokemon,
    },
  };
}
